version: '3.4'

services:
  torcbooks:
    image: ${DOCKER_REGISTRY-}torcbooks
    build:
      context: .
      dockerfile: TorcBooks/Dockerfile
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
